stages:
  - build
  - test

build_job:
  stage: build
  
  before_script:
    - apt-get update
    - apt-get install --yes cmake
  
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  
  image: gcc

test_job:
  stage: test
  
  script:
    - cd build
    - make test
    - make ExperimentalMemCheck

